name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: SampleAwsLambdaFunction Build
      run: cd SampleAwsLambdaFunction/src/SampleAwsLambdaFunction
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: SampleAwsLambdaFunction Test
      run: cd ../test/SampleAwsLambdaFunction.Test
    - name: Test
      run: dotnet test --no-build --verbosity normal
