name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  aws-lambda-build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: cd SampleAwsLambdaFunction/src/SampleAwsLambdaFunction && dotnet restore

    - name: Build
      run: cd SampleAwsLambdaFunction/src/SampleAwsLambdaFunction && dotnet build --no-restore

    - name: Test
      run: cd SampleAwsLambdaFunction/test/SampleAwsLambdaFunction.Tests && dotnet test --no-build --verbosity normal

  azure-function-build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: cd SampleAzureFunction && dotnet restore

    - name: Build
      run: cd SampleAzureFunction && dotnet build

